name: Remove AWS Access Keys from Code

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs:
  scan-and-remove-keys:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Scan for AWS Access Keys in the code
      - name: Scan for AWS Access Keys
        id: scan
        run: |
          echo "Scanning for AWS keys..."

          # Search for AWS Access Keys (the pattern typically starts with 'AKIA')
          # Using grep without -P flag to avoid compatibility issues
          found_keys=$(grep -r -o "AKIA[A-Z0-9]\{16\}" . || echo "No AWS keys found")

          if [[ "$found_keys" == "No AWS keys found" ]]; then
            echo "No AWS keys found."
          else
            echo "AWS keys found: $found_keys"
            echo "$found_keys" > found_keys.txt
          fi

      # Remove AWS Access Keys from the code
      - name: Remove AWS Access Keys from code
        if: steps.scan.outputs.found_keys != ''
        run: |
          echo "Removing AWS keys from the code..."

          # Define the pattern for AWS Access Keys
          key_pattern='AKIA[A-Z0-9]\{16\}'

          # Apply sed to all files to replace the AWS keys with a placeholder
          # We're using `-e` for expression, and ensuring files are processed correctly
          find . -type f -exec sed -i -e 's/'"$key_pattern"'/REDACTED_ACCESS_KEY/g' {} \;

          # Print out the changes for debugging
          echo "Changes made in the following files:"
          git diff --name-only

          # Check if any files were modified
          git diff --exit-code || echo "Files modified. Preparing to commit changes."

          # Stage and commit changes
          git add .
          git commit -m "Removed AWS Access Keys from the code"

      # Push changes if AWS keys were removed
      - name: Push changes
        if: steps.scan.outputs.found_keys != ''
        run: |
          git push origin HEAD
