name: Remove AWS Access Keys from Code

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs:
  scan-and-remove-keys:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Scan for AWS Access Keys in the code
      - name: Scan for AWS Access Keys
        id: scan
        run: |
          echo "Scanning for AWS keys..."

          # Search for AWS Access Keys (the pattern typically starts with 'AKIA')
          # Using grep without -P flag to avoid compatibility issues
          found_keys=$(grep -r -o "AKIA[A-Z0-9]\{16\}" . || echo "No AWS keys found")

          if [[ "$found_keys" == "No AWS keys found" ]]; then
            echo "No AWS keys found."
          else
            echo "AWS keys found: $found_keys"
            echo "$found_keys" > found_keys.txt
          fi

      # Remove AWS Access Keys from the code
      - name: Remove AWS Access Keys from code
        if: steps.scan.outputs.found_keys != ''
        run: |
          echo "Removing AWS keys from the code..."
          
          # Regex pattern to find AWS Access Keys in code
          key_pattern='AKIA[A-Z0-9]\{16\}'

          # Find and replace keys with a placeholder in all files
          find . -type f -exec sed -i 's/'"$key_pattern"'/REDACTED_ACCESS_KEY/g' {} \;

          # Check if any file was modified
          git diff --exit-c
